title: Nancy Uwera
# logo: path-to-file.png     # Uncomment and update the path if you have a logo
# show_downloads: false      # Uncomment if you want to hide download links
theme: jekyll-theme-minimal
